name: laundry_app
description: Aplikasi Laundry Online - Cuci, Setrika, Express
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  provider: ^6.0.6
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_laundrymu.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo_laundrymu.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true